server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://resteel-db.cninkrw4bfog.ap-southeast-4.rds.amazonaws.com:5432/podcast
    username: postgres
    password: resteelmonty
#    url: jdbc:postgresql://localhost:5432/podcast
#    username: postgres
#    password: root
