server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/podcast
    username: postgres
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  dir: classpath:static/episodes


